# Generated by Django 4.2.5 on 2023-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_kare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pat_desc',
            name='desc',
            field=models.TextField(default=['eere'], max_length=100),
        ),
    ]
