# Generated by Django 4.2.5 on 2023-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_kare', '0004_alter_pat_desc_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
